apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
  namespace: nginx
spec:
  template:
    spec:
      containers:
      - name: batch-container
        image: busybox:latest
        command: 
        - sh
        - -c
        - "echo 'Hello from Maruf Hossain' && sleep 10"
      restartPolicy: Never
