apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-deamon-set
  namespace: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      
      containers:
      - name: nginx-deamon-set
        image: nginx:latest

        ports:
        - containerPort: 80
